NAME: 'crt_classifier_balance'
OUTPUT_DIR: './output/cifar100_im100'
SHOW_STEP: 100
SAVE_STEP: 5
VALID_STEP: 1
INPUT_SIZE: (32, 32)
COLOR_SPACE: 'RGB'


DATASET:
  DATASET: 'IMBALANCECIFAR100'
  IMBALANCECIFAR:
    RATIO: 0.01

BACKBONE:
  TYPE: 'res32_cifar'

NETWORK:
  PRETRAINED: True
  PRETRAINED_MODEL: './output/cifar100_im100/baseline/models/epoch_200.pth'

MODULE:
  TYPE: 'GAP'

CLASSIFIER:
  TYPE: 'cRT'
  BIAS: True

LOSS:
  LOSS_TYPE: 'CrossEntropy'

TRAIN:
  BATCH_SIZE: 128
  MAX_EPOCH: 30
  NUM_WORKERS: 16
  COMBINER:
    TYPE: 'default'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.1
    MOMENTUM: 0.9
    WEIGHT_DECAY: 5e-4
  LR_SCHEDULER:
    TYPE: 'warmup'
    LR_STEP: [10, 20]
    LR_FACTOR: 0.1
    WARM_EPOCH: 5
  TENSORBOARD:
    ENABLE: True
  SAMPLER:
    TYPE: 'weighted sampler'
    WEIGHTED_SAMPLER:
      TYPE: 'balance'

  DISTRIBUTED: False
  APEX: False
  SYNCBN: True

TRANSFORMS:
  TRAIN_TRANSFORMS: ('random_crop', 'random_horizontal_flip')
  TEST_TRANSFORMS: ()

TEST:
  BATCH_SIZE: 64
  NUM_WORKERS: 8
  MODEL_FILE: 'best_model.pth'