NAME: 'cRT'
OUTPUT_DIR: './output/ImageNet_LT/'
SHOW_STEP: 500
SAVE_STEP: 1
VALID_STEP: 1
INPUT_SIZE: (224, 224)
COLOR_SPACE: 'RGB'

DATASET:
  DATASET: 'iNaturalist'
  TRAIN_JSON: 'ImageNet_LT_train.json'
  VALID_JSON: 'ImageNet_LT_val.json'

BACKBONE:
  TYPE: 'res10'

NETWORK:
  PRETRAINED: True
  PRETRAINED_MODEL: './output/ImageNet_LT/baseline/models/epoch_200.pth'

MODULE:
  TYPE: 'GAP'

CLASSIFIER:
  TYPE: 'cRT'
  BIAS: True

LOSS:
  LOSS_TYPE: 'CrossEntropy'

TRAIN:
  BATCH_SIZE: 64
  MAX_EPOCH: 30
  NUM_WORKERS: 4
  COMBINER:
    TYPE: 'default'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.1
    MOMENTUM: 0.9
    WEIGHT_DECAY: 5e-4
  LR_SCHEDULER:
    TYPE: 'multistep'
    LR_STEP: [10, 20]
    LR_FACTOR: 0.1

  TENSORBOARD:
    ENABLE: True
  SAMPLER:
    TYPE: 'weighted sampler'
    WEIGHTED_SAMPLER:
      TYPE: 'balance'

  DISTRIBUTED: False
  SYNCBN: False

TRANSFORMS:
  TRAIN_TRANSFORMS: ("random_resized_crop", "random_horizontal_flip", "color_jitter")
  TEST_TRANSFORMS: ("shorter_resize_for_crop", "center_crop")

TEST:
  BATCH_SIZE: 64
  NUM_WORKERS: 4
  MODEL_FILE: 'best_model.pth'