NAME: 'cam_generation'
OUTPUT_DIR: './output/cifar100_im100'
SHOW_STEP: 100
SAVE_STEP: 5
VALID_STEP: 1
INPUT_SIZE: (32, 32)
COLOR_SPACE: 'RGB'


DATASET:
  DATASET: 'IMBALANCECIFAR100'
  IMBALANCECIFAR:
    RATIO: 0.01
  GENERATE_CAM_BASED_DATASET: True
  CAM_DATA_JSON_SAVE_PATH: './output/cifar100_im100_CAM.json'
  CAM_DATA_SAVE_PATH: '/mnt/ramdisk/CIFAR-LT/CAM/cifar100_im100'

BACKBONE:
  TYPE: 'res32_cifar'

MODULE:
  TYPE: 'GAP'

NETWORK:
  PRETRAINED:  True
  PRETRAINED_MODEL: './output/cifar100_im100/first_stage/models/best_model.pth'


CLASSIFIER:
  TYPE: 'FC'
  BIAS: True

LOSS:
  LOSS_TYPE: 'CrossEntropy'

TRAIN:
  BATCH_SIZE: 128
  MAX_EPOCH: 160
  NUM_WORKERS: 16
  COMBINER:
    TYPE: 'default'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.1
    MOMENTUM: 0.9
    WEIGHT_DECAY: 2e-4
  LR_SCHEDULER:
    TYPE: 'warmup'
    LR_STEP: [160, 180]
    LR_FACTOR: 0.01
    WARM_EPOCH: 5
  TENSORBOARD:
    ENABLE: True
  SAMPLER:
    TYPE: 'default'

  DISTRIBUTED: False
  SYNCBN: True

TRANSFORMS:
  TRAIN_TRANSFORMS: ('random_crop', 'random_horizontal_flip')
  TEST_TRANSFORMS: ()

TEST:
  BATCH_SIZE: 64
  NUM_WORKERS: 8
  MODEL_FILE: 'best_model.pth'