NAME: 'cam-srs-drs'
OUTPUT_DIR: './output/cifar10_im100'
SHOW_STEP: 100
SAVE_STEP: 5
VALID_STEP: 1
INPUT_SIZE: (32, 32)
COLOR_SPACE: 'RGB'


DATASET:
  DATASET: 'IMBALANCECIFAR10'
  IMBALANCECIFAR:
    RATIO: 0.01
  USE_CAM_BASED_DATASET: True
  CAM_DATA_JSON_SAVE_PATH: './output/cifar10_im100_CAM.json'

NETWORK:
  PRETRAINED:  True
  PRETRAINED_MODEL: './output/cifar10_im100/first_stage/models/epoch_160.pth'

BACKBONE:
  TYPE: 'res32_cifar'

MODULE:
  TYPE: 'GAP'

CLASSIFIER:
  TYPE: 'FC'
  BIAS: True

LOSS:
  LOSS_TYPE: 'CrossEntropy'

TRAIN:
  BATCH_SIZE: 128
  MAX_EPOCH: 40
  NUM_WORKERS: 16
  COMBINER:
    TYPE: 'default'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.001
    MOMENTUM: 0.9
    WEIGHT_DECAY: 2e-4
  LR_SCHEDULER:
    TYPE: 'multistep'
    LR_STEP: [20]
    LR_FACTOR: 0.01
    WARM_EPOCH: 5
  TENSORBOARD:
    ENABLE: True
  SAMPLER:
    TYPE: 'weighted sampler'
    WEIGHTED_SAMPLER:
      TYPE: 'square'

  DISTRIBUTED: False
  SYNCBN: True

TRANSFORMS:
  TRAIN_TRANSFORMS: ('random_crop', 'random_horizontal_flip')
  TEST_TRANSFORMS: ()

TEST:
  BATCH_SIZE: 64
  NUM_WORKERS: 8
  MODEL_FILE: 'best_model.pth'