NAME: 'baseline_fcc'
OUTPUT_DIR: './output/ImageNet_LT/'
SHOW_STEP: 50
SAVE_STEP: 1
VALID_STEP: 1
INPUT_SIZE: (224, 224)
COLOR_SPACE: 'RGB'

FCC:
  WORK: True
  C_TYPE: 'edc'
  START_EPOCH: 50
  GAMMA: 0.1

DATASET:
  DATASET: 'iNaturalist'
  TRAIN_JSON: 'ImageNet_LT_train.json'
  VALID_JSON: 'ImageNet_LT_val.json'

BACKBONE:
  TYPE: 'res10'

MODULE:
  TYPE: 'GAP'

CLASSIFIER:
  TYPE: 'FC'
  BIAS: True

LOSS:
  LOSS_TYPE: 'CrossEntropy'

TRAIN:
  BATCH_SIZE: 64
  MAX_EPOCH: 200
  NUM_WORKERS: 4
  COMBINER:
    TYPE: 'fcc'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.2
    MOMENTUM: 0.9
    WEIGHT_DECAY: 1e-4
  LR_SCHEDULER:
    TYPE: 'multistep'
    LR_STEP: [160, 180]
    LR_FACTOR: 0.1
  TENSORBOARD:
    ENABLE: True
  SAMPLER:
    TYPE: 'default'

  DISTRIBUTED: False
  SYNCBN: False

TRANSFORMS:
  TRAIN_TRANSFORMS: ("random_resized_crop", "random_horizontal_flip", "color_jitter")
  TEST_TRANSFORMS: ("shorter_resize_for_crop", "center_crop")

TEST:
  BATCH_SIZE: 64
  NUM_WORKERS: 4
  MODEL_FILE: 'best_model.pth'